# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/authentication"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/currency-converter"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/demo-redis"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/github-summary"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/money-calculators"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/node-basic"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/node-discord"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/node-dynamodb"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/node-sms"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/node-typescript"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/quote-generator"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/tcp"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/tls"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/weather-tracker"
    schedule:
      interval: "weekly"
